[build]
rustflags = ["-C", "target-cpu=native"]

[alias]
lint = "clippy --all-targets --features burn-cpu,candle-cpu,candle-cuda -- -D warnings"
fmt-check = "fmt -- --check"
check-all = "check --all-targets --all-features"
test-all = "test --all-features"
coverage = "llvm-cov --all-features --workspace --summary-only --output-path coverage.txt"
